format = """
╭─ $username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration\
$python\
$time\
$line_break\
╰─\
$character"""

[directory]
style = "blue"
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
conflicted = '=${count}'
untracked = '?${count}'
stashed = "≡"
modified = '!${count}'
staged = "+${count}"
renamed = "R${count}"
deleted = "D{count}"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[fill]
symbol = '·'
style = 'bright-blue'

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
# ~/.config/starship.toml

[time]
disabled = false
format = ' $time($style) '
time_format = '%T'
utc_time_offset = '+8'
style = 'bold yellow'
# time_range = '10:00:00-14:00:00'

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
